name: CICD

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ github.event.repository.name }}
      REGISTRY: pratikparikh

    steps:

      - uses: actions/checkout@v3

      - name: Set Branch Name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set Shortened Git Hash
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images
        run: docker build . -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH }}.${{ env.SHORT_SHA }} -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH }}.latest

      - name: Push Images
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH }}.${{ env.SHORT_SHA }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH }}.latest
